### ISSUE TITLE
Create directory structures for different topics

### ISSUE THREAD

**Issue by ashwanijha04** [ashwanijha04/AmazonSDE#3]
Create directories for:
---
- Arrays and Strings
- Searching and Sorting
- Trees and Graphs
- Linked Lists
- Recursion
- Dynamic Programming

**Comment by kishanpatel22** [comment]
Hey can you assign this task to me ?

**Comment by ashwanijha04** [comment]
> Hey can you assign this task to me ?

I will have more issues for you. Don't worry about it. Will be opening it shortly

**Comment by ashwanijha04** [comment]
Closing this issue as the directory structures are created

**Comment by ashwanijha04** [comment]
> Hey can you assign this task to me ?

https://github.com/ashwanijha04/AmazonSDE/issues/7
